apiVersion: v1
kind: Service
metadata:
  labels:
    name: example
  name: example
spec:
  type: LoadBalancer
  selector:
    role: example
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
