---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    role: redis-autossl
  name: redis-autossl
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2G
