apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: skelly
  labels:
    role: skelly
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 1
       maxSurge: 2
  selector:
    matchLabels:
      role: skelly
  template:
    metadata:
      labels:
        role: skelly
    spec:
      containers:
      - name: skelly
        image: skelly
        args:
        - -listen=:8000
        - -text="(╯°□°）╯︵ ┻━┻"
        imagePullPolicy: Always
        ports:
        - name: "app"
          containerPort: 8000
          protocol: TCP
      - name: nginx
        image: auto-ssl
        imagePullPolicy: Always
        ports:
        - name: "http"
          containerPort: 80
          protocol: TCP
        - name: "https"
          containerPort: 443
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 275Mi
          requests:
            cpu: 100m
            memory: 90Mi
        volumeMounts:
        - name: nginx-config
          mountPath: /usr/local/openresty/nginx/conf
      volumes:
      - name: nginx-config
        configMap:
          name: skelly-nginx-config

