apiVersion: v1
kind: Service
metadata:
  labels:
    name: skelly
  name: skelly
spec:
  type: LoadBalancer
  selector:
    role: skelly
  ports:
  # We want both regular http and https
  # Let's Encrypt certification dance happens on both
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
